In [1]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import joblib
import numpy as np

In [2]:
dataset = pd.read_csv(r"drug_regulatory_classification_dataset.csv")
dataset.head()

,Dosage_mg,Price_Per_Unit,Production_Cost,Marketing_Spend,Clinical_Trial_Phase,Side_Effect_Severity_Score,Abuse_Potential_Score,Prescription_Rate,Hospital_Distribution_Percentage,Pharmacy_Distribution_Percentage,...,Manufacturing_Region,Requires_Cold_Storage,OTC_Flag,High_Risk_Substance,Insurance_Coverage_Percentage,Export_Percentage,Online_Sales_Percentage,Brand_Reputation_Score,Doctor_Recommendation_Rate,Target_Regulatory_Class
0,250,364.22,246.49,159132.53,3,4.26,2.52,0.74,57.93,42.07,...,South,No,No,No,64.46,41.88,41.15,6.56,0.47,Non-Regulated Drug
1,500,112.86,73.22,260595.45,2,8.12,1.80,0.48,48.00,52.00,...,East,Yes,Yes,No,93.37,10.30,50.05,4.01,0.44,Non-Regulated Drug
2,200,197.24,100.72,106818.45,3,1.58,1.47,0.93,54.48,45.52,...,North,Yes,Yes,No,64.53,34.21,46.42,5.95,0.16,Non-Regulated Drug
3,500,373.55,264.76,231304.59,4,1.72,1.61,0.54,47.20,52.80,...,North,No,Yes,No,95.21,71.04,49.52,9.65,0.76,Non-Regulated Drug
4,500,353.87,277.29,319403.02,2,9.64,0.45,0.50,86.96,13.04,...,North,No,Yes,No,98.05,70.28,44.90,1.79,0.36,Non-Regulated Drug

In [3]:
x = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

In [4]:
x.head()

,Dosage_mg,Price_Per_Unit,Production_Cost,Marketing_Spend,Clinical_Trial_Phase,Side_Effect_Severity_Score,Abuse_Potential_Score,Prescription_Rate,Hospital_Distribution_Percentage,Pharmacy_Distribution_Percentage,...,Therapeutic_Class,Manufacturing_Region,Requires_Cold_Storage,OTC_Flag,High_Risk_Substance,Insurance_Coverage_Percentage,Export_Percentage,Online_Sales_Percentage,Brand_Reputation_Score,Doctor_Recommendation_Rate
0,250,364.22,246.49,159132.53,3,4.26,2.52,0.74,57.93,42.07,...,Antibiotic,South,No,No,No,64.46,41.88,41.15,6.56,0.47
1,500,112.86,73.22,260595.45,2,8.12,1.80,0.48,48.00,52.00,...,Antidepressant,East,Yes,Yes,No,93.37,10.30,50.05,4.01,0.44
2,200,197.24,100.72,106818.45,3,1.58,1.47,0.93,54.48,45.52,...,Antiviral,North,Yes,Yes,No,64.53,34.21,46.42,5.95,0.16
3,500,373.55,264.76,231304.59,4,1.72,1.61,0.54,47.20,52.80,...,Cardiovascular,North,No,Yes,No,95.21,71.04,49.52,9.65,0.76
4,500,353.87,277.29,319403.02,2,9.64,0.45,0.50,86.96,13.04,...,Antidepressant,North,No,Yes,No,98.05,70.28,44.90,1.79,0.36

In [5]:
y.head()

0    Non-Regulated Drug
1    Non-Regulated Drug
2    Non-Regulated Drug
3    Non-Regulated Drug
4    Non-Regulated Drug
Name: Target_Regulatory_Class, dtype: str

In [6]:
# Encode target
le = LabelEncoder()
y = le.fit_transform(y.astype(str))

In [7]:
#load pipeline
preprocess_pipeline = joblib.load('preprocess_pipeline.pkl')

In [8]:
# Train-test split (before preprocessing)
X_train, X_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [9]:
# Full pipeline
pipeline = Pipeline([
    ("preprocess", preprocess_pipeline),
    ("model", SVC(probability=True))
])

In [10]:
# param = {
#     "C": [1,10],
#     "kernel": ["linear"],
#     "gamma": ["scale", "auto"]
# }

In [11]:
# grid_search = GridSearchCV(
#     estimator=svm_model,
#     param_grid=param,
#     cv=3,
#     n_jobs=-1,
# )

In [12]:
# print(set(y_train))
# print(type(y_train[0]))

In [13]:
# grid_search.fit(x_train, y_train)

In [14]:
# print("Best Parameters:", grid_search.best_params_)

In [15]:
# best_svm = grid_search.best_estimator_

In [16]:
# y_pred = best_svm.predict(x_test)

In [17]:
# print("Accuracy:", accuracy_score(y_test, y_pred))

In [18]:
# print(confusion_matrix(y_test, y_pred))

In [19]:
# print(classification_report(y_test, y_pred))

In [11]:
# Improved but faster hyperparameter space
param_dist = {
    "model__C": np.linspace(0.5, 10, 10),   # focused range
    "model__kernel": ["rbf"],               # best kernel for most datasets
    "model__gamma": ["scale", "auto", 0.01, 0.1],
    "model__class_weight": [None, "balanced"]
}

In [12]:
# Faster cross validation
cv = StratifiedKFold(
    n_splits=3,
    shuffle=True,
    random_state=42
)

In [13]:
# Faster Randomized Search
random_search = RandomizedSearchCV(
    pipeline,
    param_distributions=param_dist,
    n_iter=10,          # reduced iterations
    cv=cv,
    scoring="accuracy",
    n_jobs=-1,
    verbose=2,
    random_state=42
)

In [14]:
# Train model 
random_search.fit(X_train, y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits

RandomizedSearchCV(cv=StratifiedKFold(n_splits=3, random_state=42, shuffle=True),
                   estimator=Pipeline(steps=[('preprocess',
                                              ColumnTransformer(transformers=[('numerical',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(strategy='median')),
                                                                                               ('winsorizer',
                                                                                                Winsorizer(capping_method='iqr',
                                                                                                           fold=1.5,
                                                                                                           tail='both')),
                                                                                               ('scaler',
                                                                                                MinMaxScaler())]),
                                                                               Index(['Dosage_mg', 'Price_Pe...
      dtype='object'))])),
                                             ('model', SVC(probability=True))]),
                   n_jobs=-1,
                   param_distributions={'model__C': array([ 0.5       ,  1.55555556,  2.61111111,  3.66666667,  4.72222222,
        5.77777778,  6.83333333,  7.88888889,  8.94444444, 10.        ]),
                                        'model__class_weight': [None,
                                                                'balanced'],
                                        'model__gamma': ['scale', 'auto', 0.01,
                                                         0.1],
                                        'model__kernel': ['rbf']},
                   random_state=42, scoring='accuracy', verbose=2)

In [15]:
print("Best Parameters:", random_search.best_params_)

Best Parameters: {'model__kernel': 'rbf', 'model__gamma': 'scale', 'model__class_weight': None, 'model__C': np.float64(0.5)}

In [18]:
best_svm = random_search.best_estimator_

In [19]:
y_pred = best_svm.predict(X_test)

In [20]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7420833333333333

In [21]:
print(confusion_matrix(y_test, y_pred))

[[8053  373    0]
 [2122  852    0]
 [ 539   61    0]]

In [24]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.96      0.84      8426
           1       0.66      0.29      0.40      2974
           2       0.00      0.00      0.00       600

    accuracy                           0.74     12000
   macro avg       0.47      0.41      0.41     12000
weighted avg       0.69      0.74      0.69     12000

C:\Users\saksh\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\saksh\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\saksh\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [22]:
joblib.dump(random_search.best_estimator_, "svm_model.pkl")

['svm_model.pkl']

In [23]:
joblib.load('svm_model.pkl')

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('winsorizer',
                                                                   Winsorizer(capping_method='iqr',
                                                                              fold=1.5,
                                                                              tail='both')),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  Index(['Dosage_mg', 'Price_Per_Unit', 'Production_Cost', 'Marketing_Spend',
       'Clinical_Trial_Phase', 'Side_Effect_Severity_...
      dtype='object')),
                                                 ('catagorical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  Index(['Drug_Form', 'Therapeutic_Class', 'Manufacturing_Region',
       'Requires_Cold_Storage', 'OTC_Flag', 'High_Risk_Substance'],
      dtype='object'))])),
                ('model', SVC(C=np.float64(0.5), probability=True))])